/* ═══════════════════════════════════════════════════════════
   Gym Basics — equipment + exercise database
   Single source of truth for the equipment library, the
   exercise library, and the workout builder.
   ═══════════════════════════════════════════════════════════ */

window.GB = (function () {
  "use strict";

  /* categories */
  var CATS = { cardio: "Cardio", machines: "Machines", free: "Free weights", functional: "Functional" };

  /* muscle filter taxonomy */
  var MUSCLES = ["chest", "back", "shoulders", "arms", "legs", "glutes", "core", "full"];
  var MUSCLE_LABEL = { chest: "Chest", back: "Back", shoulders: "Shoulders", arms: "Arms", legs: "Legs", glutes: "Glutes", core: "Core", full: "Full body" };

  var GOALS = { muscle: "Build muscle", strength: "Get stronger", fatloss: "Lose fat", fitness: "Improve fitness", endurance: "Build endurance" };

  /* ── equipment ──
     id, name, cat, img, what, muscles (taxonomy keys), musclesText,
     how, beg / int / adv (level-specific use), mistake
     img    — every station now has one. `null` is still honoured: the card
              renders a typographic tile instead of asking the network for
              a file that was never there
     steps  — the numbered "how to use" list, for the demo panel
     video  — optional { src, sec }; the demo button only renders when
              a station has one, so clips can be added one at a time */
  var EQUIPMENT = [
    /* cardio */
    { id: "treadmill", name: "Treadmill", cat: "cardio", img: "img/eq-treadmill.webp",
      what: "Walking and running indoors, with control over speed and slope.",
      muscles: ["legs", "full"], musclesText: "Legs, heart and lungs",
      how: "Stand on the side rails, not the belt. Clip the red safety key to your clothing — if you slip, it stops the belt. Press Quick Start, then bring the speed up with the arrow keys.",
      steps: ["Stand on the side rails", "Clip on the red safety key", "Press Quick Start", "Raise the speed slowly", "Hands off the rails"],
      beg: "5–10 minutes of walking at 5 km/h, no incline. This is a complete warm-up on its own.",
      int: "Incline walking at 8–12% for steady cardio, or jog intervals: 1 minute easier, 1 minute harder, repeated 8–10 times.",
      adv: "Sprint intervals (30s hard / 90s easy), or a weighted-vest incline walk as a finisher.",
      mistake: "Gripping the handrails hard while you walk. It takes most of the work out of it. Let go, or slow down until you can." },

    { id: "curved-treadmill", name: "Curved treadmill", cat: "cardio", img: "img/eq-curved-treadmill.webp",
      what: "A motor-free treadmill with an arced deck — the belt only moves when you drive it with your legs.",
      muscles: ["legs", "glutes", "full"], musclesText: "Legs, glutes, heart and lungs",
      how: "Hold the rails, step on, and start walking mid-belt. Move toward the front of the curve to speed up, drift back to slow down. There is no stop button — the belt stops when you do.",
      steps: ["Hold the rails, step on mid-belt", "Start walking to drive the belt", "Move forward to speed up", "Drift back to slow down", "Slow to a stop — there is no button"],
      beg: "Short walks only, holding the rails until the moving deck feels predictable.",
      int: "Steady runs of 5–10 minutes. Expect it to feel notably harder than a motorised treadmill at the same pace.",
      adv: "All-out sprint repeats (10–20 seconds) — the self-powered belt is built for exactly this.",
      mistake: "Jumping on at speed. The belt is always live; start slow and find the curve first." },

    { id: "bike", name: "Stationary bike", cat: "cardio", img: "img/eq-bike.webp",
      what: "Cardio with almost no impact on knees and ankles — the gentlest thing in the building.",
      muscles: ["legs"], musclesText: "Legs, heart and lungs",
      how: "Set the seat so your knee stays slightly bent at the bottom of the pedal stroke. Press Quick Start and choose a low resistance level.",
      steps: ["Set the seat to hip height", "Check the knee stays slightly bent", "Press Quick Start", "Choose a low resistance", "Spin at a conversational pace"],
      beg: "10 minutes at a pace where you could still hold a conversation.",
      int: "20–30 minutes steady, or pyramid intervals: raise the resistance every 2 minutes, then step it back down.",
      adv: "Threshold work: 4–5 rounds of 4 minutes hard with 2 minutes easy between.",
      mistake: "Seat too low. It's the single most common cause of sore knees on a bike." },

    { id: "assault-bike", name: "Assault bike", cat: "cardio", img: "img/eq-assault-bike.webp",
      what: "A fan-resistance bike you drive with arms and legs together. The harder you push, the harder it pushes back.",
      muscles: ["full"], musclesText: "Whole body, heart and lungs",
      how: "Set the seat height like a normal bike, hold the moving handles, and drive with arms and legs together. Resistance is automatic — effort is the only dial.",
      steps: ["Set the seat like a normal bike", "Hold the moving handles", "Drive arms and legs together", "Sit tall throughout", "Build the pace gradually"],
      beg: "2–3 easy minutes to finish a warm-up. Keep the pace conversational; this machine escalates fast.",
      int: "Intervals: 20 seconds brisk, 40 seconds easy, for 8–10 rounds.",
      adv: "Max-calorie intervals (10–15 seconds all-out) or a 10-minute calorie target as a conditioning finisher.",
      mistake: "Starting at sprint pace. The fan punishes enthusiasm — build up over several sessions." },

    { id: "elliptical", name: "Elliptical", cat: "cardio", img: "img/eq-elliptical.webp",
      what: "Whole-body cardio where your feet never leave the pedals, so there's no impact at all.",
      muscles: ["full", "legs"], musclesText: "Legs, arms, heart and lungs",
      how: "Step on with the pedals level, hold the moving handles, and push and pull as you stride.",
      steps: ["Step on with the pedals level", "Hold the moving handles", "Push and pull as you stride", "Stand tall, weight off the handles"],
      beg: "8 minutes at resistance 3–5.",
      int: "20–25 minutes steady, alternating 2 minutes pushing mostly with legs and 2 minutes driving the handles.",
      adv: "Reverse-stride intervals and higher resistance climbs for variety on recovery days.",
      mistake: "Leaning your body weight onto the handles. Stand tall; the legs should be doing it." },

    { id: "rower", name: "Rowing machine", cat: "cardio", img: "img/eq-rower.webp",
      what: "Cardio for the whole body — about 60% legs, 30% back, 10% arms when done right.",
      muscles: ["full", "back", "legs"], musclesText: "Legs, back, arms, heart and lungs",
      how: "Strap your feet in. The order is legs → lean → arms on the way back, arms → lean → legs on the way forward. Push the floor away rather than pulling the handle.",
      steps: ["Strap your feet in", "Set the damper to 3–5", "Drive: legs, then lean, then arms", "Return: arms, then lean, then legs", "Push the floor away"],
      beg: "5 minutes easy, damper set at 3–4, focusing only on the leg push.",
      int: "2,000 m at a steady split, or 500 m repeats with 1 minute rest.",
      adv: "Interval blocks (8 × 250 m hard) or a 5,000 m row for aerobic base.",
      mistake: "Pulling with the arms first and rowing with a rounded back. Legs start every stroke." },

    { id: "stair-climber", name: "Stair climber", cat: "cardio", img: "img/eq-stair-climber.webp",
      what: "A rotating staircase. Low skill, honest effort, and one of the most effective leg-and-lungs machines in the gym.",
      muscles: ["legs", "glutes"], musclesText: "Legs, glutes, heart and lungs",
      how: "Start at a slow step rate, fingertips resting on the rails for balance only. Step fully onto each stair.",
      steps: ["Start at the slowest step rate", "Fingertips on the rails for balance only", "Step fully onto each stair", "Stand tall — do not lean on the rails"],
      beg: "3–5 minutes at the slowest setting — it is harder than it looks.",
      int: "10–15 minutes steady as a workout finisher.",
      adv: "20+ minute climbs, skip-a-step intervals, or weighted-vest sessions.",
      mistake: "Draping your whole upper body over the rails. It halves the work and rounds your back." },

    { id: "skierg", name: "SkiErg", cat: "cardio", img: "img/eq-skierg.webp",
      what: "A wall-mounted fan machine you pull downward like cross-country ski poles — cardio for the back, arms and core.",
      muscles: ["back", "core", "arms", "full"], musclesText: "Back, arms, core, heart and lungs",
      how: "Reach tall, hinge at the hips, and drive both handles down past your thighs using lats and abs, not just arms. Stand back up and repeat in rhythm.",
      steps: ["Reach tall to start", "Hinge at the hips", "Drive both handles past your thighs", "Stand back up", "Repeat in rhythm"],
      beg: "1–2 easy minutes inside a warm-up to learn the hinge rhythm.",
      int: "500 m repeats, or 30s on / 30s off intervals.",
      adv: "1,000 m+ pieces, or pair it with the rower for a full-body engine circuit.",
      mistake: "Pulling with bent, cramped arms only. The power comes from the hip hinge — think fold, not curl." },

    /* machines */
    { id: "chest-press", name: "Chest press", cat: "machines", img: "img/eq-chest-press.webp",
      what: "Everything involved in pushing, with your back fully supported and the path fixed.",
      muscles: ["chest", "shoulders", "arms"], musclesText: "Chest, front shoulders, triceps",
      how: "Set the seat so the handles line up with the middle of your chest. Push forward until your arms are almost straight, then let them come back slowly.",
      steps: ["Set the seat to line up with mid-chest", "Sit back, shoulder blades on the pad", "Push to almost-straight arms", "Return slowly over 2–3 seconds"],
      beg: "The lightest pin, 8–10 controlled repetitions. Learn the seat setting first — it matters more than the weight.",
      int: "3–4 sets of 8–12 with progressive weight; slow the lowering phase to 3 seconds.",
      adv: "A finishing exercise after barbell or dumbbell pressing: higher reps, drop sets, or single-arm pressing for balance.",
      mistake: "A seat set too high or too low, which quietly moves the work into your shoulders. Fix the seat first, every time." },

    { id: "shoulder-press", name: "Shoulder press machine", cat: "machines", img: "img/eq-shoulder-press.webp",
      what: "Overhead pressing with the balance handled for you.",
      muscles: ["shoulders", "arms"], musclesText: "Shoulders, triceps",
      how: "Set the seat so the handles sit at about ear height. Press up without locking the elbows hard, lower with control to the start.",
      steps: ["Set the seat so handles sit at ear height", "Back flat against the pad", "Press up without locking out hard", "Lower with control to the start"],
      beg: "Very light, 8–10 reps. If your lower back arches off the pad, the weight is too heavy.",
      int: "3–4 sets of 8–12 as your main press or after dumbbell work.",
      adv: "Heavy top sets, then a drop set — the fixed path makes machine presses ideal for pushing close to failure safely.",
      mistake: "Starting with the handles behind your head line. Set the seat so the press goes straight up, not backwards." },

    { id: "lat-pulldown", name: "Lat pulldown", cat: "machines", img: "img/eq-lat-pulldown.webp",
      what: "The broad muscles across your back, plus your biceps — the movement that eventually becomes a pull-up.",
      muscles: ["back", "arms"], musclesText: "Lats, upper back, biceps",
      how: "Set the thigh pads snug so you don't lift off the seat. Take the bar a bit wider than your shoulders, pull it down to your collarbone, then let it rise slowly.",
      steps: ["Set the thigh pads snug", "Grip a little wider than your shoulders", "Pull the bar to your collarbone", "Let it rise slowly", "Never behind your neck"],
      beg: "Light enough for 8 clean repetitions, feeling the shoulder blades pull down.",
      int: "3–4 sets of 8–12; vary grips (wide, neutral, underhand) across the week.",
      adv: "Strict heavy sets, pauses at the bottom, or as volume work behind weighted pull-ups.",
      mistake: "Leaning far back and yanking. Also, pulling the bar behind your neck — an old habit that's hard on the shoulders. In front, always." },

    { id: "seated-row", name: "Seated cable row", cat: "machines", img: "img/eq-seated-row.webp",
      what: "Mid-back and biceps — the pulling counterpart to the chest press, and the best posture exercise in the room.",
      muscles: ["back", "arms"], musclesText: "Mid-back, lats, biceps",
      how: "Feet on the plate, knees slightly bent, back straight. Pull the handle to your stomach keeping your elbows close to your body, then let it out slowly.",
      steps: ["Feet on the plate, knees slightly bent", "Sit tall with a straight back", "Pull the handle to your stomach", "Keep your elbows close", "Let it out slowly"],
      beg: "8–10 repetitions with a still torso. Think 'proud chest' at the end of each pull.",
      int: "3–4 sets of 8–12, pausing one second with the handle at your stomach.",
      adv: "Heavy rows with strict pauses, or single-arm rows for imbalances.",
      mistake: "Rounding your back, or swinging your whole torso to move the weight. If you're swinging, it's too heavy." },

    { id: "leg-press", name: "Leg press", cat: "machines", img: "img/eq-leg-press.webp",
      what: "Thighs and glutes — the biggest muscles you have — with your back fully supported.",
      muscles: ["legs", "glutes"], musclesText: "Quads, glutes, hamstrings",
      load: [[20, 100, 10], [100, 400, 20]],   /* plate-loaded or a deep stack; nobody presses 62.5 */
      how: "Sit back into the seat, feet shoulder-width in the middle of the plate. Push until your legs are almost straight, without snapping your knees locked. Lower under control until your knees are near a right angle.",
      steps: ["Sit back into the seat", "Feet shoulder-width, mid-plate", "Push until legs are almost straight", "Lower under control to a right angle", "Never lock your knees"],
      beg: "The lightest plate, 8–10 repetitions.",
      int: "3–4 sets of 10–15. Foot position changes emphasis: higher plate placement for glutes and hamstrings, lower for quads.",
      adv: "High-volume sets of 15–20, drop sets, or single-leg pressing after your squats.",
      mistake: "Letting the plate come down so far that your lower back lifts off the seat. Stop before that point." },

    { id: "hack-squat", name: "Hack squat", cat: "machines", img: "img/eq-hack-squat.webp",
      what: "A squat on rails: shoulders under pads, back against the pad, and a fixed path that keeps your torso honest.",
      muscles: ["legs", "glutes"], musclesText: "Quads, glutes",
      load: [[20, 100, 10], [100, 300, 20]],   /* plates a side, in 10s */
      how: "Shoulders under the pads, back flat on the pad, feet shoulder-width on the platform. Release the handles, squat until thighs are near parallel, and drive back up.",
      steps: ["Shoulders under the pads", "Back flat, feet shoulder-width", "Rotate the handles to release", "Squat to near parallel", "Drive back up and re-lock"],
      beg: "Learn the leg press first. When you graduate here, start with the empty sled.",
      int: "3–4 sets of 8–12 as a quad builder alongside free squats.",
      adv: "Heavy sets, pauses at the bottom, or narrow-stance work for quad focus.",
      mistake: "Heels lifting off the platform. If they rise, widen your stance or shorten the depth." },

    { id: "pendulum-squat", name: "Pendulum squat", cat: "machines", img: "img/eq-pendulum-squat.webp",
      what: "A squat machine that swings on an arc, matching how your body actually moves — deep, smooth, and kind to the lower back.",
      muscles: ["legs", "glutes"], musclesText: "Quads, glutes",
      load: [[20, 100, 10], [100, 250, 10]],   /* plate-loaded */
      how: "Shoulders under the pads, feet on the plate, and squat along the arc. The machine's path lets you sit deeper than most squats without your heels rising.",
      steps: ["Shoulders under the pads", "Feet flat on the plate", "Release the safety handles", "Squat along the machine's arc", "Drive up through mid-foot"],
      beg: "Skip it until machines like the leg press feel routine — then start with the empty sled.",
      int: "3 sets of 8–12 as a quad-focused alternative to the hack squat.",
      adv: "Slow 4-second lowering, pauses at depth, and drop sets — the arc keeps tension where it belongs.",
      mistake: "Chasing depth with weight on. Earn the deep position with the empty sled first." },

    { id: "leg-extension", name: "Leg extension", cat: "machines", img: "img/eq-leg-extension.webp",
      what: "The front of your thigh, in isolation.",
      muscles: ["legs"], musclesText: "Quadriceps",
      load: [[5, 80, 5], [80, 120, 10]],   /* a light stack — the quad is on its own here */
      how: "Line your knee up with the machine's pivot point, set the roller just above your ankle, and extend slowly in both directions.",
      steps: ["Line your knee up with the pivot", "Set the roller just above your ankle", "Extend slowly to straight", "Lower just as slowly"],
      beg: "Very light. This works one joint only, so weight adds up faster than you'd expect.",
      int: "3 sets of 12–15 after squats or leg press.",
      adv: "High-rep burnout sets and drop sets — a finisher, not a main lift.",
      mistake: "Too much weight, which turns it into a jerky swing and puts strain straight through the knee." },

    { id: "leg-curl", name: "Leg curl", cat: "machines", img: "img/eq-leg-curl.webp",
      what: "The back of your thigh — the muscles most beginners forget and most sprinters swear by.",
      muscles: ["legs"], musclesText: "Hamstrings",
      load: [[5, 80, 5], [80, 120, 10]],   /* as above */
      how: "Seated or lying: line your knee up with the pivot, set the roller just above your heel, and curl slowly in both directions.",
      steps: ["Line your knee up with the pivot", "Set the roller just above your heel", "Curl in smoothly", "Resist on the way back"],
      beg: "Very light, 10–12 smooth reps.",
      int: "3 sets of 10–15 in every leg session — hamstrings recover well and need the work.",
      adv: "Slow negatives and single-leg curls to fix side-to-side differences.",
      mistake: "Lifting your hips off the pad to cheat the weight up. Lighter, slower, stay glued down." },

    { id: "pec-deck", name: "Pec deck", cat: "machines", img: "img/eq-pec-deck.webp",
      what: "The chest fly, made safe: arms sweep together in a fixed arc while your back stays supported.",
      muscles: ["chest"], musclesText: "Chest",
      how: "Seat height so your elbows sit level with your shoulders when on the pads or handles. Sweep your arms together, squeeze for a second, open slowly — never behind your shoulder line.",
      steps: ["Set the seat so elbows are shoulder-height", "Forearms or hands on the pads", "Sweep your arms together", "Squeeze for a second", "Open slowly, not past your shoulders"],
      beg: "Light, 10–12 reps, opening only as far as comfortable.",
      int: "3 sets of 10–15 after pressing.",
      adv: "Slow negatives, drop sets, and long squeezes — an isolation finisher.",
      mistake: "Opening too far back with heavy weight. The stretch position under load is where chests get injured." },

    { id: "hip-thrust", name: "Hip thrust machine", cat: "machines", img: "img/eq-hip-thrust.webp",
      what: "The most direct glute exercise in the building, with your upper back braced on a pad.",
      muscles: ["glutes", "legs"], musclesText: "Glutes, hamstrings",
      load: [[20, 100, 10], [100, 250, 10]],   /* the strongest hinge in the room */
      how: "Upper back on the pad, feet flat, bar or belt over your hips. Drive your hips up until your body is a flat table, squeeze the glutes at the top, lower with control.",
      steps: ["Upper back on the pad", "Feet flat, shins vertical", "Bar or belt across your hips", "Drive up to a flat table", "Squeeze the glutes, lower with control"],
      beg: "Bodyweight or the empty setting, 10–12 reps with a real 1-second squeeze at the top.",
      int: "3–4 sets of 8–12, adding load once the top position feels solid.",
      adv: "Heavy sets of 6–10, pauses at the top, or single-leg thrusts.",
      mistake: "Overarching the lower back at the top. Finish flat like a table, chin tucked, ribs down." },

    { id: "calf-raise", name: "Calf raise", cat: "machines", img: "img/eq-calf-raise.webp",
      what: "Calves — standing machines load the straight-leg calf, seated machines the deeper muscle underneath.",
      muscles: ["legs"], musclesText: "Calves",
      load: [[10, 100, 10], [100, 250, 10]],   /* calves take more than anyone expects */
      how: "Balls of your feet on the edge, drop your heels for a full stretch, rise all the way to your toes, and pause at both ends.",
      steps: ["Balls of your feet on the edge", "Drop the heels for a full stretch", "Rise all the way to your toes", "Pause at both ends"],
      beg: "Light, 12–15 slow reps with a pause at the bottom stretch.",
      int: "3–4 sets of 10–15, twice a week — calves respond to patience.",
      adv: "Heavy single-leg work and slow 3-second negatives.",
      mistake: "Bouncing out of the stretch. The bounce belongs to the tendon, not the muscle you're trying to train." },

    /* free weights */
    { id: "dumbbells", name: "Dumbbells", cat: "free", img: "img/eq-dumbbells.webp",
      what: "The most useful objects in the building. One pair covers dozens of exercises.",
      muscles: ["full"], musclesText: "Everything, depending on the exercise",
      how: "Sold in pairs by weight, racked lightest to heaviest. Take your pair a step back from the rack so others can reach.",
      steps: ["Find your weight on the rack", "Take the pair a step back", "Train with room around you", "Put them back where they came from"],
      beg: "2–4 kg while you learn a movement. Three to start with: goblet squat, one-arm row, seated shoulder press.",
      int: "The core of your training: presses, rows, lunges, Romanian deadlifts, curls, raises.",
      adv: "Heavy dumbbell pressing and single-arm work for balance; dumbbells punish sloppy technique honestly.",
      mistake: "Not putting them back on the rack. It's the one thing everybody notices, and the easiest rule to follow." },

    { id: "barbell", name: "Olympic barbell", cat: "free", img: "img/eq-barbell.webp",
      what: "The 20 kg bar behind every classic lift: squat, deadlift, press, row.",
      muscles: ["full"], musclesText: "Everything, depending on the lift",
      how: "The bar weighs 20 kg on its own, and lifting only the bar is a normal starting point, not a beginner's embarrassment. Round plates slide onto the ends and clip in with collars.",
      steps: ["The bar alone is 20 kg", "Load plates evenly both sides", "Clip the collars on", "Strip the bar when you finish"],
      beg: "Learn movements with dumbbells or machines first; graduate to the empty bar with someone watching your form.",
      int: "The main lifts, 3–5 sets of 5–10, adding small plates over weeks — progressive overload in its purest form.",
      adv: "Heavy low-rep strength work, tempo variations, and paused lifts.",
      mistake: "Loading plates without collars. The clips take three seconds and save your shins." },

    { id: "plates", name: "Weight plates", cat: "free", img: "img/eq-plates.webp",
      what: "The currency of the gym: 1.25 to 25 kg discs that load barbells and plate-loaded machines.",
      muscles: ["full"], musclesText: "Everything they're attached to",
      how: "Carry plates with both hands, load the bar evenly side to side, and strip the bar when you're done. The small 1.25s and 2.5s are how progress actually happens.",
      steps: ["Carry with both hands", "Load evenly side to side", "Clip the collars", "Use 1.25s and 2.5s to progress", "Re-rack by size"],
      beg: "Use the small plates. Adding 2.5 kg to a machine is real progress.",
      int: "Plan jumps of 2.5–5 kg on upper-body lifts and 5–10 kg on lower-body lifts.",
      adv: "Microload: the difference between stuck and progressing is often a 1.25 on each side.",
      mistake: "Leaving plates on the bar or machine. Stripping it is part of the set." },

    { id: "kettlebells", name: "Kettlebells", cat: "free", img: "img/eq-kettlebells.webp",
      what: "Cannonballs with handles — built for swings, carries and flowing full-body work.",
      muscles: ["full", "glutes", "core"], musclesText: "Glutes, hamstrings, core, grip",
      load: [[4, 24, 2], [24, 48, 4]],   /* the sizes kettlebells are actually cast in */
      how: "The handle's offset weight makes kettlebells ideal for hinging (swings, deadlifts) and carrying. Start with goblet holds and deadlifts before anything that moves fast.",
      steps: ["Take the handle with both hands", "Start with goblet holds and deadlifts", "Hinge at the hips, not the knees", "Learn the swing before going fast"],
      beg: "Goblet squats and farmer carries — pick it up, walk tall, put it down.",
      int: "Kettlebell swings, single-arm carries and racked lunges.",
      adv: "Heavy swings, cleans and snatches — worth learning from a coach, not a mirror.",
      mistake: "Swinging with a rounded back before learning the hip hinge. The swing is a hinge, not a squat, and not an arm lift." },

    { id: "bench", name: "Adjustable bench", cat: "free", img: "img/eq-bench.webp",
      what: "The base for most dumbbell work — pressing, rowing, step-ups — and where you sit between sets.",
      muscles: ["full"], musclesText: "Whatever you do on it",
      how: "To press, sit with the dumbbells resting on your thighs, then lie back and let your thighs push them up into position. Reverse that to put them down. The backrest pins to angles from flat to upright.",
      steps: ["Set the backrest angle you need", "Sit with dumbbells on your thighs", "Lie back, thighs kick them up", "Press, then reverse to put them down"],
      beg: "Flat presses and one-arm rows with one knee on the bench.",
      int: "Incline pressing at 30–45°, split squats with a rear foot on the bench, seated shoulder work.",
      adv: "Every pressing angle in your program, plus hip thrusts off the long edge.",
      mistake: "Sitting on it with your phone while someone waits. Between sets is fine; between scrolls is not." },

    /* functional */
    { id: "cable-crossover", name: "Cable crossover", cat: "functional", img: "img/eq-cable-crossover.webp",
      what: "Two tall towers with adjustable pulleys — one machine that becomes many, because you choose the height and the handle.",
      muscles: ["chest", "back", "shoulders", "arms", "core"], musclesText: "Nearly everything, by setup",
      how: "Slide each pulley to the height you need, clip on a handle from the bin, and stand far enough back that the cable is under tension before you begin.",
      steps: ["Slide each pulley to the height you need", "Clip on a handle from the bin", "Step back until the cable is tense", "Move only the working joint"],
      beg: "Three to start with: cable row, triceps pushdown, face pull.",
      int: "Cable flys, single-arm rows, lateral raises, pallof presses — constant tension the whole movement.",
      adv: "Fly variations from every angle and slow-tempo isolation work after the heavy lifts.",
      mistake: "Standing too close to the tower, which leaves the first half of the movement doing nothing." },

    { id: "functional-trainer", name: "Functional trainer", cat: "functional", img: "img/eq-functional-trainer.webp",
      what: "A compact dual-pulley cable station — the cable crossover's apartment-sized sibling, built for single-arm and rotational work.",
      muscles: ["full", "core"], musclesText: "Nearly everything, by setup",
      how: "Two independent weight stacks with pulleys that slide to any height. Lighter stacks than a big crossover, which makes it ideal for precise, single-limb work.",
      steps: ["Slide the pulley to your working height", "Clip on the attachment", "Set your stance before the first rep", "Keep tension through the whole range"],
      beg: "Single-arm rows and presses, standing tall — let the cable teach you balance.",
      int: "Anti-rotation presses, chops and lifts for a core that resists as well as it flexes.",
      adv: "Contrast work: pair a heavy barbell lift with a fast cable version of the same pattern.",
      mistake: "Loading it like a strength machine. The stacks are light on purpose — it rewards control, not load." },

    { id: "smith-machine", name: "Smith machine", cat: "functional", img: "img/eq-smith-machine.webp",
      what: "A barbell fixed on vertical rails with hooks you can catch at any height — barbell shapes with the balance removed.",
      muscles: ["full", "legs", "chest"], musclesText: "Depends on the lift",
      load: [[10, 60, 2.5], [60, 180, 5]],   /* the carriage is counterweighted, so this is what you add */
      how: "Twist the bar to release it from the hooks, and twist back to re-rack at any point — that's the safety feature. The bar path is fixed, so set your feet where the movement feels natural.",
      steps: ["Set the bar to your starting height", "Twist to release it from the hooks", "Place your feet where it feels natural", "Twist back to re-rack at any point"],
      beg: "A confidence bridge to barbells: squats and presses with the rails as your spotter.",
      int: "Split squats, incline presses and rows where the fixed path lets you chase the muscle, not the balance.",
      adv: "Close-to-failure pressing without a spotter, and paused reps at precise depths.",
      mistake: "Squatting with feet directly under the bar as if it were a free squat. The fixed path means your feet plant slightly forward." },

    { id: "power-rack", name: "Power rack", cat: "functional", img: "img/eq-power-rack.webp",
      what: "The four-post cage around the barbell. Its whole job is letting you lift heavy alone, safely.",
      muscles: ["full"], musclesText: "Everything barbell",
      how: "Set the J-hooks at collarbone height for squats, and the long safety bars just below your lowest position — if a rep fails, the safeties catch the bar, not you.",
      steps: ["Set the J-hooks at collarbone height", "Set the safety bars below your lowest point", "Load the bar evenly", "Unrack, step back, lift", "Walk it back in to re-rack"],
      beg: "Squat holding the frame for balance, or with the empty bar and the safeties set high.",
      int: "Squats, presses and rack pulls with the safeties as your spotter.",
      adv: "Pin squats, pin presses and heavy walkouts — the rack turns failure from a danger into a data point.",
      mistake: "Using the rack for exercises that don't need it while someone waits to squat. It's the most complained-about thing in any gym." },

    { id: "squat-rack", name: "Squat rack", cat: "functional", img: "img/eq-squat-rack.webp",
      what: "The open-fronted stand that holds a barbell at shoulder height — the power rack's simpler sibling.",
      muscles: ["legs", "glutes", "full"], musclesText: "Legs, glutes, everything barbell",
      how: "Set the hooks so the bar sits at collarbone height. Step under, stand the bar off the hooks, take two steps back, squat, and walk it back in.",
      steps: ["Set the hooks at collarbone height", "Step under, bar on your back", "Stand it off the hooks", "Two steps back, then squat", "Walk it back in to re-rack"],
      beg: "The empty 20 kg bar is a real starting weight. If that's too much on day one, squat holding the frame for balance — that counts too.",
      int: "Back squats and front squats, 3–5 sets, adding small plates weekly.",
      adv: "Heavy squat sessions with spotter arms attached, plus overhead pressing out of the hooks.",
      mistake: "Walking the bar out five steps. Two steps back is enough — every extra step is wasted strength." }
  ];

  /* ── exercises ──
     level = minimum level (1 beg / 2 int / 3 adv)
     role  = warmup | main | accessory | core | conditioning | cooldown
     kit   = machine | cable | dumbbell | barbell | kettlebell | bodyweight | cardio
     rx    = default prescription per level {sets, reps, rest(sec)}
     goals = which goals this suits */
  var EXERCISES = [
    /* ── warm-up / cardio / conditioning ── */
    { id: "treadmill-walk", name: "Treadmill walk", muscle: "full", musclesText: "Heart, lungs, legs", kit: "cardio", eq: "treadmill",
      level: 1, role: "warmup", goals: ["fitness", "fatloss", "endurance", "muscle", "strength"],
      rx: { 1: { time: "5–10 min easy" }, 2: { time: "5 min brisk" }, 3: { time: "5 min brisk" } },
      position: "Stand on the side rails, clip on the safety key, start the belt slow.",
      movement: "Walk tall at a conversational pace; add a little incline if it feels too easy.",
      breathing: "Through the nose if you can — it keeps the pace honest.",
      mistakes: ["Gripping the handrails hard", "Starting at a jog before the body is warm"],
      cue: "You should finish warmer, not tired.",
      var1: "Flat, easy pace.", var2: "Add 5–8% incline.", var3: "Finish with 3 × 30 s strides.",
      safety: "This is the warm-up — save effort for the session." },

    { id: "incline-walk", name: "Incline treadmill walk", muscle: "legs", musclesText: "Legs, glutes, heart", kit: "cardio", eq: "treadmill",
      level: 1, role: "conditioning", goals: ["fatloss", "endurance", "fitness"],
      rx: { 1: { time: "10 min at 6–8%" }, 2: { time: "15 min at 10–12%" }, 3: { time: "20 min at 12–15%" } },
      position: "Set incline before speed. Hands off the rails.",
      movement: "Long, tall steps; drive through the whole foot.",
      breathing: "Steady rhythm — if you can't speak a sentence, lower the incline.",
      mistakes: ["Holding the rails and leaning back (it erases the incline)"],
      cue: "Posture tall, eyes forward, hands free.",
      var1: "6–8% incline, easy pace.", var2: "10–12%, brisk.", var3: "12–15% or add a weighted vest.",
      safety: "Step onto the rails before changing settings." },

    { id: "row-intervals", name: "Rower intervals", muscle: "full", musclesText: "Legs, back, lungs", kit: "cardio", eq: "rower",
      level: 2, role: "conditioning", goals: ["endurance", "fatloss", "fitness"],
      rx: { 2: { time: "6 × 250 m, 1 min rest" }, 3: { time: "8 × 250 m or 4 × 500 m" } },
      position: "Feet strapped, damper 4–6, straight back at the catch.",
      movement: "Legs → lean → arms; arms → lean → legs. Power comes from the push.",
      breathing: "Exhale on the drive, inhale on the recovery.",
      mistakes: ["Arms pulling first", "Rounding the back at the catch"],
      cue: "Push the floor away — the handle follows.",
      var1: "Row easy 5 minutes continuous.", var2: "250 m repeats at a strong pace.", var3: "500 m repeats holding your target split.",
      safety: "Sore lower back means the lean is happening too early." },

    { id: "bike-sprints", name: "Assault bike sprints", muscle: "full", musclesText: "Whole body, lungs", kit: "cardio", eq: "assault-bike",
      level: 3, role: "conditioning", goals: ["fatloss", "endurance", "fitness"],
      rx: { 3: { time: "8 × 15 s hard / 45 s easy" } },
      position: "Seat set like a road bike; hold the moving handles.",
      movement: "Drive arms and legs together; sit tall through the sprint.",
      breathing: "It will take care of itself — recover fully between rounds.",
      mistakes: ["Sprinting from a cold start", "Letting form collapse in the last rounds"],
      cue: "The last sprint should look like the first.",
      var1: "Steady easy spin only.", var2: "20 s brisk / 40 s easy.", var3: "15 s all-out / 45 s easy.",
      safety: "Genuinely maximal — earn it with weeks of intervals first." },

    /* ── chest ── */
    { id: "machine-chest-press", name: "Machine chest press", muscle: "chest", musclesText: "Chest, front shoulders, triceps", kit: "machine", eq: "chest-press",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 3, reps: "10–15", rest: 60 } },
      position: "Seat set so the handles line up with mid-chest; feet flat, back against the pad.",
      movement: "Push to almost-straight arms, then return slowly over 2–3 seconds.",
      breathing: "Exhale as you push, inhale as the handles come back.",
      mistakes: ["Seat height wrong (work drifts into shoulders)", "Bouncing out of the bottom"],
      cue: "Push the handles away and keep your shoulder blades against the pad.",
      var1: "Lightest pin, focus on the seat setup.", var2: "Add weight weekly; 3-second lowering.", var3: "Use as a finisher after free-weight pressing; drop sets.",
      safety: "Shoulder-friendly by design — stay inside a comfortable range." },

    { id: "db-bench-press", name: "Dumbbell bench press", muscle: "chest", musclesText: "Chest, front shoulders, triceps", kit: "dumbbell", eq: "bench",
      level: 2, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 120 }, 3: { sets: 4, reps: "6–10", rest: 120 } },
      position: "Sit with dumbbells on your thighs; lie back and kick them up one at a time. Feet flat, slight arch, shoulder blades pinched.",
      movement: "Lower to the sides of your chest with elbows about 45° from your body; press up and slightly together.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Elbows flared to 90°", "Dropping the weights from the top at the end (roll back and sit up instead)"],
      cue: "Bend the bar — elbows under wrists the whole way.",
      var1: "Machine chest press instead.", var2: "Moderate dumbbells, 3-second lowering.", var3: "Heavy sets of 6–8 or pause each rep on the chest.",
      safety: "To finish a set, bring the weights to your thighs and sit up — never drop them past your shoulders." },

    { id: "incline-db-press", name: "Incline dumbbell press", muscle: "chest", musclesText: "Upper chest, shoulders, triceps", kit: "dumbbell", eq: "bench",
      level: 2, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 4, reps: "8–12", rest: 90 } },
      position: "Bench at 30–45°. Same setup as the flat press.",
      movement: "Lower to the top of the chest; press up and slightly back.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Bench too steep (it becomes a shoulder press)", "Arching to turn it flat"],
      cue: "Press toward the ceiling, not toward your face.",
      var1: "Incline machine press.", var2: "30° incline, controlled tempo.", var3: "45° heavy sets, or slow 4-second negatives.",
      safety: "Same dismount as the flat press: weights to thighs, then sit up." },

    { id: "barbell-bench", name: "Barbell bench press", muscle: "chest", musclesText: "Chest, shoulders, triceps", kit: "barbell", eq: "bench",
      level: 3, role: "main", goals: ["strength", "muscle", "fatloss"],
      rx: { 3: { sets: 4, reps: "5–8", rest: 180 } },
      position: "Eyes under the bar, feet planted, shoulder blades pinched and pressed into the bench.",
      movement: "Unrack, lower to mid-chest with forearms vertical, press back to the start.",
      breathing: "Big breath at the top, exhale through the press.",
      mistakes: ["Bouncing off the chest", "Benching heavy alone with no spotter or safeties"],
      cue: "Meet the bar with your chest, then push yourself away from it.",
      var1: "Machine chest press.", var2: "Dumbbell bench press.", var3: "Add pauses, tempo work, or close-grip sets.",
      safety: "Use a spotter or rack safeties for heavy sets. No collars when benching alone." },

    { id: "pec-deck-fly", name: "Pec deck fly", muscle: "chest", musclesText: "Chest", kit: "machine", eq: "pec-deck",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "10–12", rest: 60 }, 2: { sets: 3, reps: "10–15", rest: 60 }, 3: { sets: 3, reps: "12–15", rest: 45 } },
      position: "Seat set so elbows are level with shoulders; back flat on the pad.",
      movement: "Sweep arms together, squeeze one second, open slowly to a comfortable stretch.",
      breathing: "Exhale together, inhale apart.",
      mistakes: ["Opening too far back under load", "Jerking the start of each rep"],
      cue: "Hug a barrel — elbows slightly bent and fixed.",
      var1: "Light, short range.", var2: "Full comfortable range, 3 sets.", var3: "Drop set to finish.",
      safety: "Never fight for range behind your shoulder line." },

    { id: "cable-fly", name: "Cable fly", muscle: "chest", musclesText: "Chest, front shoulders", kit: "cable", eq: "cable-crossover",
      level: 2, role: "accessory", goals: ["muscle"],
      rx: { 2: { sets: 3, reps: "10–15", rest: 60 }, 3: { sets: 3, reps: "12–15", rest: 45 } },
      position: "Pulleys at shoulder height, one handle each side, staggered stance a step forward.",
      movement: "Sweep hands together in a wide arc until they meet; return slowly.",
      breathing: "Exhale together, inhale apart.",
      mistakes: ["Turning it into a press by bending the elbows", "Standing too close to the towers"],
      cue: "Elbows locked slightly bent — draw a circle, not a line.",
      var1: "Pec deck instead.", var2: "Shoulder-height pulleys.", var3: "Low-to-high and high-to-low angles across sets.",
      safety: "Step forward out of the stretch to finish, don't let the stacks yank you back." },

    { id: "pushup", name: "Push-up", muscle: "chest", musclesText: "Chest, shoulders, triceps, core", kit: "bodyweight", eq: null,
      level: 1, role: "accessory", goals: ["fitness", "muscle", "endurance", "fatloss"],
      rx: { 1: { sets: 2, reps: "5–10", rest: 60 }, 2: { sets: 3, reps: "10–20", rest: 60 }, 3: { sets: 3, reps: "15–25", rest: 45 } },
      position: "Hands under shoulders, body one straight line from head to heels.",
      movement: "Lower chest to just above the floor, elbows about 45°, press back up.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Hips sagging", "Half range at speed"],
      cue: "Squeeze glutes and abs — a moving plank.",
      var1: "Hands on a bench or bar (incline push-up).", var2: "Full push-ups from the floor.", var3: "Feet elevated or add a weight plate on your back.",
      safety: "If the hips sag, raise the hands — an honest incline beats a broken plank." },

    /* ── back ── */
    { id: "lat-pulldown-ex", name: "Lat pulldown", muscle: "back", musclesText: "Lats, upper back, biceps", kit: "machine", eq: "lat-pulldown",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 4, reps: "8–12", rest: 90 } },
      position: "Thigh pads snug, grip a bit wider than shoulders.",
      movement: "Pull the bar to your collarbone, leading with the elbows; let it rise slowly.",
      breathing: "Exhale down, inhale up.",
      mistakes: ["Leaning far back and yanking", "Pulling behind the neck"],
      cue: "Elbows into your back pockets.",
      var1: "Light pin, feel the shoulder blades pull down.", var2: "Rotate grips across the week.", var3: "Volume work behind weighted pull-ups; pause at the chest.",
      safety: "In front of the face, always." },

    { id: "seated-cable-row-ex", name: "Seated cable row", muscle: "back", musclesText: "Mid-back, lats, biceps", kit: "machine", eq: "seated-row",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 4, reps: "8–12", rest: 75 } },
      position: "Feet on the plate, knees soft, back tall.",
      movement: "Pull the handle to your stomach, elbows close; return slowly until arms are long.",
      breathing: "Exhale in, inhale out.",
      mistakes: ["Swinging the torso", "Shrugging the shoulders up"],
      cue: "Proud chest at the end of every pull.",
      var1: "Light, torso still.", var2: "1-second pause at the stomach.", var3: "Heavy strict sets or single-arm cable rows.",
      safety: "If you're rocking, it's too heavy." },

    { id: "db-row", name: "One-arm dumbbell row", muscle: "back", musclesText: "Lats, mid-back, biceps", kit: "dumbbell", eq: "bench",
      level: 2, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 75 }, 3: { sets: 4, reps: "6–10", rest: 90 } },
      position: "One knee and hand on the bench, other foot planted, back flat like a table.",
      movement: "Pull the dumbbell to your hip, not your armpit; lower long and slow.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Twisting the torso to heave the weight", "Pulling to the shoulder"],
      cue: "Start each rep by sliding your shoulder blade back.",
      var1: "Seated cable row instead.", var2: "Moderate weight, strict.", var3: "Heavy 'kroc' rows for high reps, grip allowing.",
      safety: "Flat back throughout — set up in a mirror the first few times." },

    { id: "barbell-row", name: "Barbell row", muscle: "back", musclesText: "Whole back, rear shoulders, biceps", kit: "barbell", eq: "barbell",
      level: 3, role: "main", goals: ["strength", "muscle", "fatloss"],
      rx: { 3: { sets: 4, reps: "6–10", rest: 120 } },
      position: "Hinge to about 45°, bar hanging from straight arms, back flat.",
      movement: "Pull the bar to your lower ribs; lower under control without standing up.",
      breathing: "Exhale as you pull, inhale as you lower.",
      mistakes: ["Standing further up every rep", "Jerking with the lower back"],
      cue: "The torso is a table — only the arms and shoulder blades move.",
      var1: "One-arm dumbbell row.", var2: "Chest-supported row on an incline bench.", var3: "Pendlay rows from the floor for strict power.",
      safety: "Your hinge must be solid before this earns a place." },

    { id: "pullup", name: "Pull-up", muscle: "back", musclesText: "Lats, upper back, biceps, core", kit: "bodyweight", eq: "power-rack",
      level: 3, role: "main", goals: ["strength", "muscle", "fitness", "fatloss"],
      rx: { 3: { sets: 4, reps: "5–10", rest: 120 } },
      position: "Hands a bit wider than shoulders, full hang, shoulders engaged.",
      movement: "Pull chin over the bar leading with the chest; lower all the way down.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Kipping half reps", "Chin poking to sneak over the bar"],
      cue: "Pull the bar to you, chest proud.",
      var1: "Lat pulldown builds toward this.", var2: "Band-assisted or slow negatives.", var3: "Add weight on a belt once 8 strict reps are easy.",
      safety: "Full hang, controlled lowering — elbows earn their health there." },

    { id: "face-pull", name: "Face pull", muscle: "shoulders", musclesText: "Rear shoulders, upper back", kit: "cable", eq: "cable-crossover",
      level: 2, role: "accessory", goals: ["muscle", "fitness"],
      rx: { 2: { sets: 3, reps: "12–15", rest: 60 }, 3: { sets: 3, reps: "15–20", rest: 45 } },
      position: "Rope attachment at upper-chest height; step back until the cable is taut.",
      movement: "Pull the rope toward your face, splitting the ends past your ears; elbows high.",
      breathing: "Exhale as you pull, inhale as you return.",
      mistakes: ["Turning it into a heavy row", "Elbows dropping"],
      cue: "Thumbs to your ears, elbows wide.",
      var1: "Light band pull-aparts.", var2: "Strict, light, high reps.", var3: "Add a pause with the rope split.",
      safety: "This is posture medicine — keep it light forever." },

    /* ── shoulders ── */
    { id: "machine-shoulder-press", name: "Machine shoulder press", muscle: "shoulders", musclesText: "Shoulders, triceps", kit: "machine", eq: "shoulder-press",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 3, reps: "10–15", rest: 60 } },
      position: "Seat so handles sit at ear height; back against the pad, feet flat.",
      movement: "Press up without crashing the elbows locked; lower with control.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Arching the lower back off the pad", "Half-lowering each rep"],
      cue: "Ribs down, press straight up.",
      var1: "Very light — learn the range.", var2: "Main press or after dumbbell work.", var3: "Heavy top set, then a drop set.",
      safety: "If the lower back arches, the weight is too heavy." },

    { id: "db-shoulder-press", name: "Dumbbell shoulder press", muscle: "shoulders", musclesText: "Shoulders, triceps", kit: "dumbbell", eq: "bench",
      level: 1, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 4, reps: "6–10", rest: 120 } },
      position: "Seated with back support, dumbbells at shoulder height, palms forward or neutral.",
      movement: "Press up until arms are long, weights close together at the top; lower to ear height.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Pressing forward instead of up", "Flaring the ribs"],
      cue: "Biceps finish by your ears.",
      var1: "Light pair, seated with full back support.", var2: "Moderate weight, full range.", var3: "Standing press for full-body tension.",
      safety: "Kick the dumbbells up from your thighs one at a time." },

    { id: "lateral-raise", name: "Lateral raise", muscle: "shoulders", musclesText: "Side shoulders", kit: "dumbbell", eq: "dumbbells",
      level: 2, role: "accessory", goals: ["muscle"],
      rx: { 2: { sets: 3, reps: "12–15", rest: 45 }, 3: { sets: 4, reps: "12–20", rest: 45 } },
      position: "Standing tall, light dumbbells at your sides, slight lean forward.",
      movement: "Raise the arms out to shoulder height, elbows soft; lower slower than you lifted.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Swinging with the hips", "Going above shoulder height with shrugged traps"],
      cue: "Pour the jugs — pinkies lead slightly at the top.",
      var1: "Skip until pressing is routine.", var2: "Light and strict.", var3: "Cable laterals, drop sets, 20-rep burnouts.",
      safety: "The lightest dumbbells on the rack are the right ones for months." },

    { id: "overhead-press", name: "Barbell overhead press", muscle: "shoulders", musclesText: "Shoulders, triceps, core", kit: "barbell", eq: "squat-rack",
      level: 3, role: "main", goals: ["strength", "muscle", "fatloss"],
      rx: { 3: { sets: 4, reps: "5–8", rest: 180 } },
      position: "Bar at collarbone in the rack; grip just outside shoulders, elbows slightly forward, glutes tight.",
      movement: "Press the bar past your face, then push your head 'through the window' so the bar finishes over mid-foot.",
      breathing: "Big breath before the press, exhale over the top.",
      mistakes: ["Leaning back into a standing incline press", "Bar drifting forward"],
      cue: "Squeeze glutes like the floor owes you money — the body is the platform.",
      var1: "Machine shoulder press.", var2: "Seated dumbbell press.", var3: "Push press for overload, strict press for honesty.",
      safety: "Take it out of a rack, not off the floor, until cleans are trained." },

    /* ── arms ── */
    { id: "triceps-pushdown", name: "Triceps pushdown", muscle: "arms", musclesText: "Triceps", kit: "cable", eq: "cable-crossover",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "10–12", rest: 60 }, 2: { sets: 3, reps: "10–15", rest: 45 }, 3: { sets: 3, reps: "12–15", rest: 45 } },
      position: "High pulley, bar or rope, elbows pinned to your sides.",
      movement: "Push down until arms are straight, pause, let it rise to a right angle.",
      breathing: "Exhale down, inhale up.",
      mistakes: ["Elbows drifting forward", "Leaning your bodyweight onto the bar"],
      cue: "Elbows are hinges glued to your ribs.",
      var1: "Light, straight-bar.", var2: "Rope attachment, split at the bottom.", var3: "Single-arm reverse-grip pushdowns.",
      safety: "Light and strict beats heavy and hunched." },

    { id: "db-curl", name: "Dumbbell curl", muscle: "arms", musclesText: "Biceps, forearms", kit: "dumbbell", eq: "dumbbells",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "10–12", rest: 60 }, 2: { sets: 3, reps: "8–12", rest: 45 }, 3: { sets: 3, reps: "10–15", rest: 45 } },
      position: "Standing tall or seated, dumbbells hanging at your sides, palms forward.",
      movement: "Curl to shoulder height without moving the elbows; lower slow and long.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Swinging from the hips", "Half-lowering"],
      cue: "Elbows stay welded to your sides.",
      var1: "Light, seated against a backrest.", var2: "Alternating or hammer-grip curls.", var3: "Incline bench curls for the long stretch.",
      safety: "The swing robs the biceps and taxes the back — lighter, stricter." },

    { id: "ez-curl", name: "Barbell curl", muscle: "arms", musclesText: "Biceps, forearms", kit: "barbell", eq: "barbell",
      level: 2, role: "accessory", goals: ["muscle"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 60 }, 3: { sets: 3, reps: "8–12", rest: 60 } },
      position: "Standing, shoulder-width grip on a barbell or EZ bar.",
      movement: "Curl to shoulder height, elbows still; 3-second lowering.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Bouncing at the bottom", "Elbows creeping forward at the top"],
      cue: "Grow tall and pin the elbows.",
      var1: "Dumbbell curls.", var2: "EZ bar for friendlier wrists.", var3: "Strict curls against a wall, or 21s.",
      safety: "Straight-bar curls that hurt the wrists → switch to the EZ bar." },

    { id: "overhead-triceps", name: "Overhead triceps extension", muscle: "arms", musclesText: "Triceps (long head)", kit: "dumbbell", eq: "dumbbells",
      level: 2, role: "accessory", goals: ["muscle"],
      rx: { 2: { sets: 3, reps: "10–15", rest: 45 }, 3: { sets: 3, reps: "10–15", rest: 45 } },
      position: "Seated or standing, one dumbbell held in both hands overhead.",
      movement: "Lower the weight behind your head to a full stretch; extend back up.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Elbows flaring wide", "Cutting the stretch short"],
      cue: "Elbows point at the ceiling the whole time.",
      var1: "Cable pushdowns instead.", var2: "Single dumbbell, both hands.", var3: "Cable overhead extensions for constant tension.",
      safety: "Keep the weight modest — the elbow position is unforgiving." },

    /* ── legs & glutes ── */
    { id: "leg-press-ex", name: "Leg press", muscle: "legs", musclesText: "Quads, glutes, hamstrings", kit: "machine", eq: "leg-press",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "10–15", rest: 90 }, 3: { sets: 4, reps: "10–15", rest: 90 } },
      position: "Back and hips glued to the seat, feet shoulder-width mid-plate.",
      movement: "Lower to a right angle at the knees, press to almost-straight legs.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Lower back peeling off the seat at depth", "Knees snapping locked"],
      cue: "Push the world away, hips stay planted.",
      var1: "Lightest plate, 8–10 reps.", var2: "Foot position by target: high for glutes, low for quads.", var3: "Sets of 15–20, drop sets, or single-leg pressing.",
      safety: "Never let the knees crash toward your chest." },

    { id: "goblet-squat", name: "Goblet squat", muscle: "legs", musclesText: "Quads, glutes, core", kit: "dumbbell", eq: "dumbbells",
      level: 1, role: "main", goals: ["muscle", "strength", "fitness", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "8–10", rest: 90 }, 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 3, reps: "10–15", rest: 75 } },
      position: "Hold one dumbbell upright against your chest, elbows down, feet shoulder-width.",
      movement: "Sit down between your heels until elbows brush your knees; stand tall.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Heels lifting", "Chest collapsing forward"],
      cue: "The dumbbell is a bowl of soup — spill nothing.",
      var1: "Squat to a bench, stand up.", var2: "Heavier bell, slow 3-second descent.", var3: "A warm-up for barbell squats.",
      safety: "The counterweight makes this the friendliest squat in the gym." },

    { id: "db-lunge", name: "Dumbbell lunge", muscle: "legs", musclesText: "Quads, glutes, balance", kit: "dumbbell", eq: "dumbbells",
      level: 2, role: "accessory", goals: ["muscle", "fitness", "fatloss", "endurance"],
      rx: { 2: { sets: 3, reps: "8–10 / leg", rest: 90 }, 3: { sets: 3, reps: "10–12 / leg", rest: 75 } },
      position: "Dumbbells at your sides, feet hip-width, eyes forward.",
      movement: "Step forward, lower the back knee to just above the floor, push back to standing.",
      breathing: "Inhale down, exhale back up.",
      mistakes: ["Front knee collapsing inward", "Tiny steps that jam the knee"],
      cue: "Down like an elevator, not forward like a lean.",
      var1: "Split squats holding a rail.", var2: "Walking lunges down the floor.", var3: "Rear-foot-elevated (Bulgarian) split squats.",
      safety: "Balance first, load second — bodyweight until the wobble is gone." },

    { id: "bulgarian-split", name: "Bulgarian split squat", muscle: "legs", musclesText: "Quads, glutes", kit: "dumbbell", eq: "bench",
      level: 3, role: "accessory", goals: ["muscle", "strength", "fatloss"],
      rx: { 3: { sets: 3, reps: "8–12 / leg", rest: 90 } },
      position: "Rear foot laces-down on a bench, front foot a long step ahead, dumbbells at your sides.",
      movement: "Lower straight down until the rear knee nearly touches; drive up through the front heel.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Front foot too close to the bench", "Bouncing off the back leg"],
      cue: "All the weight lives in the front foot.",
      var1: "Regular split squats.", var2: "Bodyweight, holding a rail.", var3: "Front-foot-elevated for extra range.",
      safety: "Famous for next-day soreness — start with 2 sets." },

    { id: "romanian-deadlift", name: "Romanian deadlift", muscle: "glutes", musclesText: "Hamstrings, glutes, lower back", kit: "dumbbell", eq: "dumbbells",
      level: 2, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 120 }, 3: { sets: 4, reps: "6–10", rest: 120 } },
      position: "Dumbbells or bar in front of your thighs, knees soft, shoulders back.",
      movement: "Push your hips back and slide the weight down your legs until the hamstrings pull like guitar strings; stand by squeezing the glutes.",
      breathing: "Inhale on the way down, exhale up.",
      mistakes: ["Rounding the back to chase depth", "Bending the knees into a squat"],
      cue: "Close a car door behind you with your hips.",
      var1: "Practice the hinge with a broomstick along your spine.", var2: "Dumbbells, mid-shin depth.", var3: "Barbell RDLs, 2-second pause at the stretch.",
      safety: "Depth is wherever your flat back ends. Nothing below that counts." },

    { id: "deadlift", name: "Barbell deadlift", muscle: "full", musclesText: "Hamstrings, glutes, back, grip", kit: "barbell", eq: "barbell",
      level: 3, role: "main", goals: ["strength", "muscle", "fatloss"],
      rx: { 3: { sets: 3, reps: "3–6", rest: 240 } },
      position: "Bar over mid-foot, shins close, hands just outside legs, back flat, chest proud.",
      movement: "Push the floor away and stand tall; the bar stays against your legs both ways.",
      breathing: "Big breath and brace before each pull; reset on the floor.",
      mistakes: ["Rounding the lower back", "Jerking the bar off the floor", "Bar drifting away from the legs"],
      cue: "Squeeze the bar off the floor — it's a push, not a yank.",
      var1: "Romanian deadlifts with dumbbells.", var2: "Trap-bar deadlifts.", var3: "Conventional pulls; consider straps for heavy back-off sets.",
      safety: "The one lift most worth an hour of coaching before loading." },

    { id: "barbell-squat", name: "Barbell back squat", muscle: "legs", musclesText: "Quads, glutes, core", kit: "barbell", eq: "squat-rack",
      level: 3, role: "main", goals: ["strength", "muscle", "fatloss"],
      rx: { 3: { sets: 4, reps: "5–8", rest: 240 } },
      position: "Bar on the upper back shelf (not the neck), hands comfortable, two steps back from the hooks.",
      movement: "Sit down between your heels to at least parallel; stand without the chest collapsing.",
      breathing: "Big breath at the top, hold through the rep, exhale at lockout.",
      mistakes: ["Knees caving inward", "Chasing depth with a rounded back", "Good-morning out of the hole"],
      cue: "Spread the floor with your feet; big air, proud chest.",
      var1: "Goblet squats.", var2: "The empty bar with safeties set.", var3: "Pause squats and tempo work.",
      safety: "Always squat inside a rack with safeties near your bottom position." },

    { id: "hip-thrust-ex", name: "Hip thrust", muscle: "glutes", musclesText: "Glutes, hamstrings", kit: "machine", eq: "hip-thrust",
      level: 2, role: "main", goals: ["muscle", "strength", "fatloss"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 90 }, 3: { sets: 4, reps: "6–10", rest: 120 } },
      position: "Upper back on the pad or bench, feet flat under the knees, load across the hips.",
      movement: "Drive hips up to a flat table, one-second squeeze, lower with control.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Overarching at the top", "Pushing through the toes"],
      cue: "Chin tucked, ribs down, squeeze like you mean it.",
      var1: "Bodyweight glute bridges from the floor.", var2: "Machine or barbell, moderate load.", var3: "Heavy sets, pauses, or single-leg thrusts.",
      safety: "Height at the top comes from glutes, not lower-back arch." },

    { id: "leg-extension-ex", name: "Leg extension", muscle: "legs", musclesText: "Quadriceps", kit: "machine", eq: "leg-extension",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "10–12", rest: 60 }, 2: { sets: 3, reps: "12–15", rest: 60 }, 3: { sets: 3, reps: "15–20", rest: 45 } },
      position: "Knee lined up with the pivot, roller just above the ankle.",
      movement: "Extend to straight, one-second squeeze, lower slow.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Kicking the weight up with momentum"],
      cue: "Squeeze the thigh at the top like flexing for a photo.",
      var1: "Very light, learn the pivot lineup.", var2: "After squats or presses.", var3: "Drop sets and slow negatives to finish.",
      safety: "Single-joint machines multiply weight fast — patience." },

    { id: "leg-curl-ex", name: "Leg curl", muscle: "legs", musclesText: "Hamstrings", kit: "machine", eq: "leg-curl",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "10–12", rest: 60 }, 2: { sets: 3, reps: "10–15", rest: 60 }, 3: { sets: 3, reps: "10–15", rest: 60 } },
      position: "Knee at the pivot, roller just above the heel.",
      movement: "Curl the roller in smoothly; resist it on the way back.",
      breathing: "Exhale in, inhale out.",
      mistakes: ["Hips lifting off the pad", "Jerky half reps"],
      cue: "Drag your heels to your glutes.",
      var1: "Light, both legs.", var2: "In every leg session.", var3: "Single-leg curls, slow negatives.",
      safety: "Hamstrings hate surprises — warm up before heavy curls." },

    { id: "calf-raise-ex", name: "Calf raise", muscle: "legs", musclesText: "Calves", kit: "machine", eq: "calf-raise",
      level: 1, role: "accessory", goals: ["muscle"],
      rx: { 1: { sets: 2, reps: "12–15", rest: 45 }, 2: { sets: 3, reps: "10–15", rest: 45 }, 3: { sets: 4, reps: "8–15", rest: 60 } },
      position: "Balls of the feet on the edge, heels free to travel.",
      movement: "Full stretch at the bottom, full rise to the toes, pause at both ends.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Bouncing", "Tiny mid-range pulses"],
      cue: "Two floors: basement stretch, penthouse squeeze.",
      var1: "Bodyweight on a step.", var2: "Machine, 3-second negatives.", var3: "Heavy single-leg work.",
      safety: "Full range or it's an ankle bounce, not a calf raise." },

    { id: "kb-swing", name: "Kettlebell swing", muscle: "glutes", musclesText: "Glutes, hamstrings, core, grip", kit: "kettlebell", eq: "kettlebells",
      level: 2, role: "conditioning", goals: ["fatloss", "fitness", "endurance"],
      rx: { 2: { sets: 4, reps: "15", rest: 60 }, 3: { sets: 5, reps: "20", rest: 45 } },
      position: "Feet wider than shoulders, bell a foot ahead; hinge, flat back, hike it between your legs.",
      movement: "Snap the hips forward — the bell floats to chest height on its own. Let it swing back and repeat.",
      breathing: "Sharp exhale on every hip snap.",
      mistakes: ["Squatting instead of hinging", "Lifting with the arms", "Leaning back at the top"],
      cue: "Hips throw, arms steer.",
      var1: "Master the Romanian deadlift first.", var2: "Moderate bell, sets of 15.", var3: "Heavy bell, or swing intervals on the clock.",
      safety: "Learn the hinge cold before making it fast." },

    /* ── core ── */
    { id: "plank", name: "Plank", muscle: "core", musclesText: "Abs, deep core, shoulders", kit: "bodyweight", eq: null,
      level: 1, role: "core", goals: ["fitness", "muscle", "strength", "fatloss", "endurance"],
      rx: { 1: { sets: 2, reps: "20–30 s", rest: 45 }, 2: { sets: 3, reps: "40–60 s", rest: 45 }, 3: { sets: 3, reps: "60 s+", rest: 45 } },
      position: "Forearms down, elbows under shoulders, body one straight line.",
      movement: "Don't move — squeeze glutes and abs, and breathe.",
      breathing: "Slow and steady; the brace stays on between breaths.",
      mistakes: ["Hips sagging or hiked", "Holding breath"],
      cue: "Tuck your tail, squeeze your fists, push the floor away.",
      var1: "Knees down or hands elevated.", var2: "Full plank, 45–60 s.", var3: "Weighted, or lift one arm at a time.",
      safety: "A short honest plank beats a long saggy one." },

    { id: "dead-bug", name: "Dead bug", muscle: "core", musclesText: "Deep core, coordination", kit: "bodyweight", eq: null,
      level: 1, role: "core", goals: ["fitness", "strength", "endurance"],
      rx: { 1: { sets: 2, reps: "6–8 / side", rest: 45 }, 2: { sets: 3, reps: "8–10 / side", rest: 45 }, 3: { sets: 3, reps: "10–12 / side", rest: 30 } },
      position: "On your back, arms to the ceiling, knees over hips at 90°.",
      movement: "Lower one arm and the opposite leg toward the floor; return; switch sides.",
      breathing: "Exhale as the limbs lower, keeping the lower back pressed down.",
      mistakes: ["Lower back arching off the floor", "Racing through reps"],
      cue: "Your lower back is glued to the mat — that's the exercise.",
      var1: "Arms only or legs only.", var2: "Full opposite arm-and-leg.", var3: "Hold a light plate, or add a band.",
      safety: "The friendliest core drill for cranky backs." },

    { id: "cable-crunch", name: "Cable crunch", muscle: "core", musclesText: "Abs", kit: "cable", eq: "cable-crossover",
      level: 2, role: "core", goals: ["muscle"],
      rx: { 2: { sets: 3, reps: "12–15", rest: 45 }, 3: { sets: 3, reps: "15–20", rest: 45 } },
      position: "Kneel below a high pulley holding a rope beside your head.",
      movement: "Crunch your ribs toward your hips — the elbows chase the knees; uncurl slowly.",
      breathing: "Exhale as you crunch, inhale up.",
      mistakes: ["Bowing from the hips with a rigid spine", "Sitting back instead of curling down"],
      cue: "Roll up like a wave, not fold like a hinge.",
      var1: "Floor crunches with a slow curl.", var2: "Moderate stack, strict curl.", var3: "Heavier stack — abs like weight too.",
      safety: "The hips stay still; only the spine curls." },

    { id: "hanging-knee-raise", name: "Hanging knee raise", muscle: "core", musclesText: "Lower abs, hip flexors, grip", kit: "bodyweight", eq: "power-rack",
      level: 2, role: "core", goals: ["muscle", "fitness"],
      rx: { 2: { sets: 3, reps: "8–12", rest: 60 }, 3: { sets: 3, reps: "12–15", rest: 60 } },
      position: "Full hang from a bar, shoulders engaged.",
      movement: "Curl your knees toward your chest, tilting the pelvis; lower without swinging.",
      breathing: "Exhale up, inhale down.",
      mistakes: ["Swinging into momentum", "Lifting only the thighs with no pelvic curl"],
      cue: "Bring your belt buckle to your chin.",
      var1: "Lying leg raises on a bench.", var2: "Strict knee raises.", var3: "Straight-leg raises to the bar.",
      safety: "Kill the swing between reps — dead hang, then lift." },

    { id: "pallof-press", name: "Pallof press", muscle: "core", musclesText: "Obliques, deep core", kit: "cable", eq: "functional-trainer",
      level: 2, role: "core", goals: ["strength", "fitness"],
      rx: { 2: { sets: 3, reps: "8–10 / side", rest: 45 }, 3: { sets: 3, reps: "10–12 / side", rest: 45 } },
      position: "Stand side-on to a chest-height cable, handle held at your sternum.",
      movement: "Press the handle straight out and hold two seconds while the cable tries to twist you; return.",
      breathing: "Exhale as you press out, breathe shallow in the hold.",
      mistakes: ["Letting the torso rotate", "Standing too close (no tension)"],
      cue: "You are a statue — the cable loses.",
      var1: "Half-kneeling with a light band.", var2: "Standing, 2-second holds.", var3: "Add a slow overhead raise in the hold.",
      safety: "Anti-rotation is the point; nothing should visibly move." },

    /* ── warm-up: easy cardio ──
       treadmill-walk above is the third option */
    { id: "bike-warmup", name: "Easy bike", muscle: "legs", musclesText: "Legs, heart and lungs", kit: "cardio", eq: "bike",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "5 min easy" }, 2: { time: "5 min easy" }, 3: { time: "5 min easy" } },
      position: "Seat height so your knee stays slightly bent at the bottom of the stroke.",
      movement: "Spin at a low resistance — conversational the whole way.",
      breathing: "Through the nose if you can.",
      mistakes: ["Starting at a resistance that turns the warm-up into the workout"],
      cue: "Warmer, not tired.",
      var1: "5 minutes, lowest resistance.", var2: "5 minutes, raise resistance slightly each minute.", var3: "5 minutes finishing with two 20-second pickups.",
      safety: "The gentlest warm-up in the building — good on sore knees." },

    { id: "rower-warmup", name: "Easy row", muscle: "full", musclesText: "Legs, back, heart and lungs", kit: "cardio", eq: "rower",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "5 min easy" }, 2: { time: "5 min easy" }, 3: { time: "5 min easy" } },
      position: "Feet strapped, damper 3–4, straight back at the catch.",
      movement: "Legs → lean → arms, unhurried. Let the stroke lengthen as you warm.",
      breathing: "Exhale on the drive, inhale on the recovery.",
      mistakes: ["Yanking with the arms before the legs have pushed"],
      cue: "Push the floor away — the handle follows.",
      var1: "5 minutes easy, thinking only about the leg push.", var2: "5 minutes building pace.", var3: "5 minutes with three 15-second bursts.",
      safety: "Stop if your lower back rounds — shorten the reach instead." },

    /* ── warm-up: dynamic prep ── */
    { id: "arm-circles", name: "Arm circles", muscle: "shoulders", musclesText: "Shoulders, upper back", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "10 each way" }, 2: { time: "10 each way" }, 3: { time: "12 each way" } },
      position: "Stand tall with your arms out to the sides at shoulder height.",
      movement: "Draw small circles forward, growing them gradually, then reverse.",
      breathing: "Easy and steady — no holding it.",
      mistakes: ["Shrugging the shoulders up toward the ears", "Rushing so the circles get sloppy"],
      cue: "Long arms, quiet shoulders.",
      var1: "Small circles only.", var2: "Small to large, both directions.", var3: "Add a slow overhead reach at the end.",
      safety: "Stay inside a comfortable range — this is preparation, not a stretch." },

    { id: "hip-circles", name: "Hip circles", muscle: "legs", musclesText: "Hips, lower back", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "10 each way" }, 2: { time: "10 each way" }, 3: { time: "10 each way" } },
      position: "Feet shoulder-width, hands on your hips.",
      movement: "Circle the hips slowly in one direction, then the other, keeping your feet planted.",
      breathing: "Relaxed throughout.",
      mistakes: ["Circling so fast the lower back does the work"],
      cue: "Move the hips, not the shoulders.",
      var1: "Small, slow circles.", var2: "Full range both directions.", var3: "Add a deep squat hold between directions.",
      safety: "Back off the range if anything pinches." },

    { id: "leg-swings", name: "Leg swings", muscle: "legs", musclesText: "Hips, hamstrings, glutes", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "10 / side" }, 2: { time: "10 / side" }, 3: { time: "12 / side" } },
      position: "Hold a rack or wall for balance, standing tall on one leg.",
      movement: "Swing the free leg forward and back, relaxed, letting the range grow with each rep.",
      breathing: "Don't hold your breath.",
      mistakes: ["Arching the lower back to force height", "Swinging so hard you lose balance"],
      cue: "Loose leg, still torso.",
      var1: "Small forward and back swings only.", var2: "Add side-to-side swings.", var3: "Both directions plus a slow controlled hold at the top.",
      safety: "Hold on to something — this is not a balance test." },

    { id: "cat-cow", name: "Cat–cow", muscle: "core", musclesText: "Spine, core", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "8 slow reps" }, 2: { time: "8 slow reps" }, 3: { time: "10 slow reps" } },
      position: "On all fours, hands under shoulders, knees under hips.",
      movement: "Round the back and drop the head, then reverse into a gentle arch with the chest open.",
      breathing: "Exhale as you round, inhale as you arch — the breath sets the pace.",
      mistakes: ["Racing through it", "Cranking the neck at either end"],
      cue: "Move one vertebra at a time.",
      var1: "Small range, slow.", var2: "Full comfortable range.", var3: "Add a few side bends afterwards.",
      safety: "Use a mat; nothing here should pinch." },

    { id: "band-pull-apart", name: "Band pull-apart", muscle: "back", musclesText: "Upper back, rear shoulders", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "12 reps" }, 2: { time: "15 reps" }, 3: { time: "15–20 reps" } },
      position: "Hold a light band at shoulder height, arms straight out in front.",
      movement: "Pull the band apart until your arms are wide, squeezing the shoulder blades, then return slowly.",
      breathing: "Exhale as you pull apart.",
      mistakes: ["A band so heavy the elbows bend", "Shrugging instead of squeezing the blades"],
      cue: "Blades together, shoulders down.",
      var1: "Lightest band, 12 reps.", var2: "Add reps before load.", var3: "Pause two seconds at the widest point.",
      safety: "Prep for pressing — keep it light on purpose." },

    { id: "squat-prep", name: "Bodyweight squat", muscle: "legs", musclesText: "Quads, glutes, hips", kit: "bodyweight",
      level: 1, role: "warmup", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "10 slow reps" }, 2: { time: "10 slow reps" }, 3: { time: "12 slow reps" } },
      position: "Feet shoulder-width, toes turned slightly out, arms forward for balance.",
      movement: "Sit down to a comfortable depth and stand back up, taking three seconds down.",
      breathing: "Inhale down, exhale up.",
      mistakes: ["Knees collapsing inward", "Rushing to the bottom"],
      cue: "Chest proud, knees tracking over the toes.",
      var1: "Hold a rack for balance and go to a box.", var2: "Full depth, slow tempo.", var3: "Add a two-second pause at the bottom.",
      safety: "Depth is whatever is comfortable today — it improves on its own." },

    /* ── cool-down: stretches and breathing ── */
    { id: "quad-stretch", name: "Standing quad stretch", muscle: "legs", musclesText: "Quads, hip flexors", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "40s / side" } },
      position: "Stand tall, holding something for balance.",
      movement: "Draw one heel toward your backside, knees level, and hold. Swap sides.",
      breathing: "Slow and even — the stretch releases on the exhale.",
      mistakes: ["Arching the lower back", "Letting the knee drift out to the side"],
      cue: "Squeeze the glute and stand tall — the stretch deepens without pulling harder.",
      var1: "Hold a wall and keep it gentle.", var2: "30 seconds each side, no support.", var3: "Add a slight forward hip push.",
      safety: "Mild tension, never pain, and no bouncing." },

    { id: "hamstring-stretch", name: "Hamstring stretch", muscle: "legs", musclesText: "Hamstrings, calves", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "40s / side" } },
      position: "One heel on a low bench, that leg straight, standing tall.",
      movement: "Hinge forward from the hips until you feel the back of the thigh lengthen, and hold.",
      breathing: "Exhale slowly into the hold.",
      mistakes: ["Rounding the back to reach further", "Locking the knee hard"],
      cue: "Lead with the chest, not the head.",
      var1: "Foot on a very low step.", var2: "Standard bench height.", var3: "Add a gentle ankle pull toward you.",
      safety: "Stop at mild tension — this is recovery, not a contest." },

    { id: "hip-flexor-stretch", name: "Kneeling hip flexor stretch", muscle: "legs", musclesText: "Hip flexors, quads", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "40s / side" } },
      position: "Half-kneeling on a mat, one knee down, the other foot forward and flat.",
      movement: "Squeeze the back glute and ease the hips forward until the front of the back hip lengthens.",
      breathing: "Slow exhales; let the hip settle rather than forcing it.",
      mistakes: ["Arching the lower back instead of moving the hip", "Letting the front knee collapse inward"],
      cue: "Tuck the tailbone under, then move forward.",
      var1: "Small range, hands on the front knee.", var2: "Full range, tall torso.", var3: "Add an overhead reach on the kneeling side.",
      safety: "Pad the down knee. Especially worth doing after a day of sitting." },

    { id: "calf-stretch", name: "Calf stretch", muscle: "legs", musclesText: "Calves, achilles", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "30s / side" } },
      position: "Hands on a wall, one foot back with the leg straight and heel down.",
      movement: "Ease the hips toward the wall until the back calf lengthens, and hold.",
      breathing: "Steady and slow.",
      mistakes: ["Lifting the back heel", "Turning the back foot out"],
      cue: "Back heel glued down, toes pointing forward.",
      var1: "Gentle, both hands on the wall.", var2: "Straight-leg version.", var3: "Repeat with the back knee slightly bent for the lower calf.",
      safety: "Useful after any running, incline walking or stair work." },

    { id: "chest-stretch", name: "Doorway chest stretch", muscle: "chest", musclesText: "Chest, front shoulders", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "40s / side" } },
      position: "Forearm on a rack upright or door frame, elbow at shoulder height.",
      movement: "Turn your body slowly away from the arm until the chest opens, and hold.",
      breathing: "Exhale into the turn.",
      mistakes: ["Shrugging the shoulder toward the ear", "Turning so far it pinches at the front of the shoulder"],
      cue: "Chest wide, shoulder down and back.",
      var1: "Elbow slightly below shoulder height.", var2: "Elbow at shoulder height.", var3: "Three heights per side — low, middle, high.",
      safety: "Ease off immediately if the front of the shoulder pinches." },

    { id: "lat-stretch", name: "Lat stretch", muscle: "back", musclesText: "Lats, upper back", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "30s / side" }, 2: { time: "30s / side" }, 3: { time: "40s / side" } },
      position: "Hold a rack upright at arm's length, feet back, hips pushed away.",
      movement: "Let the hips sink back and down until the side of your back lengthens, and hold.",
      breathing: "Long exhales — the ribs drop and the stretch deepens on its own.",
      mistakes: ["Gripping so hard the shoulders shrug", "Holding the breath"],
      cue: "Hips away, ribs down.",
      var1: "Two hands, gentle lean.", var2: "One side at a time.", var3: "Add a slow side bend at the end of the hold.",
      safety: "Good after any pulling day." },

    { id: "childs-pose", name: "Child's pose", muscle: "back", musclesText: "Lower back, hips, shoulders", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "45–60s" }, 2: { time: "45–60s" }, 3: { time: "60s" } },
      position: "Kneel on a mat, big toes together, knees apart, and sit back toward your heels.",
      movement: "Walk the hands forward and let the chest sink toward the floor. Stay and breathe.",
      breathing: "Slow nasal breathing, feeling the back of the ribs expand.",
      mistakes: ["Treating it as a race", "Forcing the hips down when they are not ready"],
      cue: "Let gravity do it.",
      var1: "Knees narrow, hands under the forehead.", var2: "Knees wide, arms long.", var3: "Walk the hands to each side for the lats.",
      safety: "Skip or narrow the knees if it bothers your knees." },

    { id: "box-breathing", name: "Box breathing", muscle: "full", musclesText: "Nervous system, breathing", kit: "bodyweight",
      level: 1, role: "cooldown", goals: ["muscle", "strength", "fatloss", "fitness", "endurance"],
      rx: { 1: { time: "2 min" }, 2: { time: "2 min" }, 3: { time: "3 min" } },
      position: "Sit or lie down somewhere quiet, shoulders relaxed.",
      movement: "Breathe in for four, hold for four, out for four, hold for four. Repeat.",
      breathing: "That is the whole exercise.",
      mistakes: ["Straining to hold longer than is comfortable"],
      cue: "Shorten the count to three if four feels forced.",
      var1: "Three-count box, two minutes.", var2: "Four-count box.", var3: "Five-count box, three minutes.",
      safety: "The switch from training back to the rest of your day. Never hold a breath to the point of discomfort." }
  ];

  /* ── what the weight dropdown offers ──
     A rack does not step evenly all the way up: dumbbells go up in
     2.5s to 30 and in 5s after that, a leg press in 10s to 100 and 20s
     after that, and nobody has ever loaded 62.5 kg on one. So a ladder
     is a list of [from, to, step] segments rather than a single step.

     These are the defaults per kit. A station whose stack disagrees
     carries its own `load` (see leg-press, hack-squat, smith-machine
     and the rest below), and an exercise may override its station in
     turn — one lift on a shared station is the case that needs it.
     Kept here with the rest of the equipment data so the increments
     are edited where the machines are described, not in the UI code. */
  var LOADS = {
    dumbbell:   [[2.5, 30, 2.5], [30, 50, 5]],
    barbell:    [[20, 60, 2.5], [60, 200, 5]],
    machine:    [[5, 100, 5], [100, 150, 10]],
    cable:      [[2.5, 60, 2.5], [60, 100, 5]],
    kettlebell: [[4, 24, 2], [24, 48, 4]]
  };

  /* Reps completed. Whole numbers to 20, because that is the range
     every prescription on this site lives in, then the round numbers
     people actually count in above it. */
  var REPS = (function () {
    var out = [];
    for (var i = 1; i <= 20; i++) out.push(i);
    return out.concat([25, 30, 35, 40, 50]);
  })();

  /* index by id */
  var EQ_BY_ID = {}; EQUIPMENT.forEach(function (e) { EQ_BY_ID[e.id] = e; });
  var EX_BY_ID = {}; EXERCISES.forEach(function (x) { EX_BY_ID[x.id] = x; });

  return {
    CATS: CATS, MUSCLES: MUSCLES, MUSCLE_LABEL: MUSCLE_LABEL, GOALS: GOALS,
    EQUIPMENT: EQUIPMENT, EXERCISES: EXERCISES, EQ_BY_ID: EQ_BY_ID, EX_BY_ID: EX_BY_ID,
    LOADS: LOADS, REPS: REPS
  };
})();
